    # Configuration de la base de données H2 en mémoire


# spring.application.name=demo
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# spring.h2.console.enabled=true
  
  # Configuration pour une base de données PostgreSQL

# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}

# spring.jpa.hibernate.ddl-auto=update

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=TON_EMAIL
# spring.mail.password=TON_APP_PASSWORD
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://dpg-d7g19457vvec73ejrd30-a.oregon-postgres.render.com:5432/connexion_financiere_db
spring.datasource.username=connexion_financiere_db_user
spring.datasource.password=20Nwt97Jk2lbtS7D9s0HlYeWfRWZLKT4

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect